# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
    include:
    - SPRINT
 paths:
    include:
    - FutureNHS/*

jobs:
- job: CheckChangesInPaths
  pool:
    vmImage: 'windows-latest'
  steps: 
  - powershell: |
      $url="$(System.CollectionUri)/$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.ID)/commits/$(Build.SourceVersion)/changes?api-version=5.1"
      $result = Invoke-RestMethod -Uri $url -Headers @{Authorization = "Bearer $(System.AccessToken)"} -Method GET
                       
      $changesFolder  = $result.changes | Where-Object{$_.item.gitObjectType -match "tree"} | Select-Object -Property {$_.item.path}
     
      foreach($path in $changesFolder ){
        if($path -match '/FutureNHS'){
          echo "##vso[task.setvariable variable=FutureNHS;isOutput=true]$True"
          break
        }
      }
    name: ChangesInPaths

  variables:
   solution: 'FutureNHS.sln'
   buildPlatform: 'x64'
   buildConfiguration: 'Release'

- job: BuildFutureNHS
  pool :
    vmImage: 'windows-latest'
  dependsOn: CheckChangesInPaths
  condition: eq(dependencies.CheckChangesInPaths.outputs['ChangesInPaths.FutureNHS'], 'true') 
  steps:
   - task: UseDotNet@2
     inputs:
      packageType: 'sdk'
      version: '6.0.x'

   - task: DotNetCoreCLI@2
     inputs:
      command: 'restore'
      projects: '$(Build.SourcesDirectory)/$(working-dir)/**/*.csproj'
      feedsToUse: 'select'

   - task: DotNetCoreCLI@2
     inputs:
      command: 'build'
      configuration: 'Release'
      projects: '$(Build.SourcesDirectory)/$(working-dir)/**/*.csproj'
      feedsToUse: 'select'

   - task: DotNetCoreCLI@2
     inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '$(Build.SourcesDirectory)/$(working-dir)/**/*.csproj'
      zipAfterPublish: false

   - task: CopyFiles@2
     inputs:
      SourceFolder: '$(Build.SourcesDirectory)/$(working-dir)/FutureNHS.Api/bin/Release/net6.0/publish'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

   - task: PublishPipelineArtifact@1
     inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'FNHSApi'
      publishLocation: 'pipeline'
    
