# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- SPRINT

pool:
  vmImage: 'windows-latest'

variables:
  solution: '*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: MSBuild@1
  inputs:
    solution: '*.sln'
    msbuildArchitecture: 'x64'
    configuration: 'Release'
    restoreNugetPackages: true
    createLogFile: true
    logFileVerbosity: 'detailed'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/FutureNHS.Api'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'FNHSApi'
    publishLocation: 'pipeline'