# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
    include:
    - TRY-RI-VNEXT-APP

steps:
- template: futurenhs.api/azure-pipelines-api.yml
- template: FutureNHS.Data/azure-pipeline.yml
- template: MVCForum/azure-pipelines.yml
- template: futurenhs.app/azure-pipelines.yml
